### PR TITLE
update scroll to botom

### PR DESCRIPTION
**Pull request by joancf**
If the page does not detect the final "element" but does not scroll down after a while it returns

### CODE REVIEW

**Comment by joancf** [comment]
Joe, thanks for your software, it works pretty well
I have also done some changes to export to gdf format to be imported on gephi (but that's another commit...)

**Comment by jcontini** [comment]
Hey @joancf, thanks for this! I just tried it on my mac, but it seemed to finish prematurely and not scroll to bottom of the page. Does it work reliably for you?

Gephi format sounds brilliant, I looked into it but haven't tried it yet. My whole goal was the graph visualization so this makes a lot of sense

**Comment by joancf** [comment]
Hi @jcontini ,
It depends on the speed of your computer.
What it checks is that in the 0.25 seconds  that you wait for the scroll, the size has changed, (and that at least 100 times the page has been extended)
so if the page goes slow it can jump of after 25 seconds. 
One option is to reset the counter if the size changes : adding the else option below and then maybe reducing the number of sleeps to wait to maybe 40

    ```
     if  last_height == height :
                                print("%d steps, Blocked! at size %d" % (sleeps, last_height))
				time.sleep(0.25)
                if  sleeps >40:   #10 seconds 
				pass
                    break
    else:
               sleeps=0;
```
you can look at my code and branches, for gephi export but I changed the code a lot.. and now i'm trying to do an interface (but I'm not used to python tk)

**Comment by jcontini** [comment]
Hi @joancf, thanks again for this. I ended up re-writing everything and using m.facebook.com instead of the full site to index profiles. Works much better!

**Pull request closed without merging**
